FROM python:3.12-slim

# Working Dir
WORKDIR /code

# Copy backend files
COPY ./backend/requirements.txt /code/requirements.txt

# Install backend dependencies
RUN pip install  --no-cache-dir --upgrade -r /code/requirements.txt

# Copy python code 
COPY ./backend /code
# Copy react build files to 
COPY ./frontend/dist /code/dist

# start the uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
